### ISSUE TITLE
exposure event <> duration

### ISSUE THREAD

**Issue by dirkdevriendt** [eu-parc/aggregate-exposure-modelling#1]
The texts are contradictory, so you probably need to take a step back and evaluate what detail you want to be able to express (e.g. do you want to have the option of combining a single high level exposure event with a long term low intensity exposure on the same external exposure or would that be two separate external exposures)
e.g. the example (every day for 300 days over a 1 year period) can only be modeled if you drop a part of the information

That said, the way it is described, exposure duration is the length of time property for a continuous contact, which defines an exposure event. If the exposure is intermittent, it is described to have one duration and encompass multiple events (or the same exemplar event that occurs multiple times, e.g. 10 minutes every day). So the exposure event needs a duration too, but the 10 mins, 300 days, 1 year, frequency, average event and specific events may all need representation.

**Comment by JasperEngel** [comment]
Sketch it indicate my interpretation of the issue. Both an exposure event and the "overall" period of exposure (multiple events) are need a duration. 
![Exposure_duration](https://github.com/eu-parc/aggregate-exposure-modelling/assets/122374091/d70cc78d-58d3-4881-99ec-1107e322f387)

**Comment by jwkruisselbrink** [comment]
I think exposure events should be the "elementary building blocks" of complex (external) exposure patterns. I distinguish four types composed of two different choices: 1) discrete (bolus) exposure versus continuous exposure, 2) one-time exposure versus repetitive exposure. See image below. In such a case, exposure duration would apply only for repetitive exposures, being the duration of the time frame in which the repetition takes place.

![image](https://github.com/eu-parc/aggregate-exposure-modelling/assets/17898794/c3246e4a-cdde-44c0-b066-bb9fde53bc59)

![image](https://github.com/eu-parc/aggregate-exposure-modelling/assets/17898794/c13d5369-fa37-4a8c-a29a-5b1bac63ac1a)

**Comment by jwkruisselbrink** [comment]
Main conclusion from meeting (31/8):
- Comment: a general definition of exposure event is required that is compatible across different domains. An example was provided for the concept of an event in dermal exposure modelling being different from that in dietary exposure modelling.
- Comment: the conceptual model should not be too complex, but complete enough to facilitate the needs/data of the case studies. It should also be sufficient to anticipate in use of e.g., PBK models for aggregating external exposure estimates from different models, possibly expressed at different time-scales and units.
- Comment: it was accepted that there is a distinction between an event duration and an exposure duration (of repetitive exposure events).
- Action point: David and Henk to proposal of general definition of exposure event and schema for the level of detail.

**Comment by jwkruisselbrink** [comment]
Closed. Further discussion as part of issue #20.
