### ISSUE TITLE
External exposure <> exposure level

### ISSUE THREAD

**Issue by martinebakker** [eu-parc/aggregate-exposure-modelling#13]
What is the difference between 'external exposure' and 'exposure level'? I.m.o. they are the same.

**Comment by jwkruisselbrink** [comment]
The external exposure represents a complex entity, as a collection of pieces of information; source, substance, route, etc. Exposure level was supposed to represent the actual value of the exposure. I.e., for oral exposure of 4 mg/kg bw/day, the level is 4, the unit is mg/kg bw,.. and the frequency would be per day.
