### ISSUE TITLE
output of aggregate exposure model

### ISSUE THREAD

**Issue by martinebakker** [eu-parc/aggregate-exposure-modelling#14]
In my view the output of the aggregate exposure model is 'aggregate internal exposure' rather than 'internal exposure'. The latter is a result of the PBK-model. The aggregate exposure model needs to add up all internal exposures (with the same unit of time, e.g 1 day), resulting in an aggregate internal exposure.
Question: do we need to include in the data model that the aggregate exposure model is/needs to be person-oriented?

**Comment by jwkruisselbrink** [comment]
Comments from discussion (31/8):
- Internal exposure seems more general, because the conceptual model is more generic, and also used for single route exposures, in which case no aggregation takes place. That being said, the "Aggregate exposure modelling" box may also be changed to "Internal exposure modelling".
- Action point: Martine to make proposal (picture).

**Comment by martinebakker** [comment]
I have made a picture of the 'core' of the scheme as I think it should look like: [Issue#14.pptx](https://github.com/eu-parc/aggregate-exposure-modelling/files/12583573/Issue.14.pptx)

**Comment by jwkruisselbrink** [comment]
![image](https://github.com/eu-parc/aggregate-exposure-modelling/assets/17898794/751b3016-1768-4d14-ad9d-9b765cd10071)

**Comment by jwkruisselbrink** [comment]
Decision: leave the diagram as it is, but change the name to "Aggregate and internal dose modelling". Aggregation within routes can take place at input. Aggregation over over different routes takes place behind the absorption barrier (in blood). Note: for absorption factors, also a summation step is needed which is implicit in PBK modelling.

**Comment by jwkruisselbrink** [comment]
Below is a proposal for the envisioned workflow for aggregate exposure modelling that should clarify that aggregation takes place at different levels (within routes / between routes):

![image](https://github.com/eu-parc/aggregate-exposure-modelling/assets/17898794/92fe6cc2-be94-44ee-987b-83ac475ca8d0)
