### ISSUE TITLE
Include sub-domain HBM in main diagram

### ISSUE THREAD

**Issue by jwkruisselbrink** [eu-parc/aggregate-exposure-modelling#15]
Include the sub-domain of HBM to clarify the overlap and cross-links with this sub-domain.

**Comment by JasperEngel** [comment]
The red boxed in the figure indicate terms that are expected to overlap with the sub-domain of HBM.
![Overlap_HBM_domain](https://github.com/eu-parc/aggregate-exposure-modelling/assets/122374091/4ef58d17-7778-4877-afe7-bd8e1428a339)
