### ISSUE TITLE
[TERM] Inner exposure surface

### ISSUE THREAD

**Issue by clementblassiau** [eu-parc/aggregate-exposure-modelling#18]
It seems to me that the term 'inner exposure surface' is used in a different sense from the definition.

In the AD6.3 glossary, the following definitions were proposed:

**Exposure surface**. [adapted from (IPCS and IOMC 2004)].
A surface on a target where a substance is present. A distinction could be made between the surfaces inside the body, i.e. _inner exposure surfaces_, and those outside the body, i.e. _outer exposure surfaces_, that have in common to be _located before an absorption barrier_. Examples of outer exposure surfaces include the exterior of an eyeball, the skin surface, and a conceptual surface over the nose and open mouth. Examples of inner exposure surfaces include the gastrointestinal tract, the respiratory tract, and the urinary tract lining.

**Internal exposure**. [adapted from (US EPA et al. 2008); and (IPCS and IOMC 2004)].
The amount of substance that passes through an absorption barrier and reaches a targeted biological matrix. These include, for example, exposure of urine, blood, or even of specific organs.

---> According to this definition, inner exposure surface is a possible site of external exposure (before an absorption barrier). The site of internal exposure (after an absorption barrier) could be called a 'targeted biological matrix'.

**Comment by jwkruisselbrink** [comment]
Action point meeting (31/8): Clement and David to propose improved schema as picture (in this issue).

**Comment by clementblassiau** [comment]
Proposal of improvement done, in relation to the previous comment.
Commit 6898bcab54fd9fbd261f441ea2fa59f383507ba3 to commit 058c9fa4357ea6a6ad4ce30726c8a5472c9aeb7b.

Previous diagram :
[
![image](https://github.com/eu-parc/aggregate-exposure-modelling/assets/138027155/ffb38457-9737-4398-a928-e397f5c006e5)
](url)

New proposal :
[
![image](https://github.com/eu-parc/aggregate-exposure-modelling/assets/138027155/b1987521-d5a8-4000-ab98-fcee3c9dcd43)
](url)
