### ISSUE TITLE
[OTHER] Sub-group: exposure source

### ISSUE THREAD

**Issue by clementblassiau** [eu-parc/aggregate-exposure-modelling#19]
The term 'environmental source' has not been defined in the AD6.3 glossary. It appears only once in the body of the text and refers to exposure sources indicated in the diagram 'Sub-group: exposure source', **and also to minimally processed foods**.

I propose not to include this term in the conceptual model 'Sub-group: exposure source', but rather to include the following elements:

- dust, 
- indoor air, 
- outdoor air, 
- soil, 
- surface water, 
- drinking water, 
- food, 
- consumer products (include pharmaceuticals, don't include food, as suggested in the glossary of AD6.3),
- occupational sources,
- pet fur ?,
- waste ?.

**Comment by clementblassiau** [comment]
Proposal for a new diagram in line with the previous comment.
Corresponds to the commit a7eb94ad493e4a0939bd8e4defd35a7ba08fc1e4.
[UPDATE: correction made according to Arno's comment on dust]

**Comment by jwkruisselbrink** [comment]
Proposal Clement:

![image](https://github.com/eu-parc/aggregate-exposure-modelling/assets/17898794/bd5240fc-508e-4975-b179-3e7046ecce28)

Is there a need to create hierarchy levels between these different exposure sources?

**Comment by ArnoVand** [comment]
Seems like in the new version of the diagram 'Dust' [CB: it was a forgetting. Now added. Thanks] and 'Pharmaceuticals' are missing, which could be important exposure sources. 

If we would use some hierarchy levels between different exposure sources, I would suggest grouping them per exposure route (oral, dermal or inhalatory). Between these routes there are distinct differences (absorption through GI tract _vs._ absorption in the lungs), but within one route the exposure sources could be treated in the same way, e.g. treating the oral exposure from potatoes and beef as one sum of oral exposures. 
Some of the sources could be in multiple groups, e.g. water can lead to both oral and dermal exposure.

**Comment by jwkruisselbrink** [comment]
Accepted. 
Pet fur may be deleted because it will not be considered as an exposure source in the context of the aggregate exposure modelling work. Waste is still relevant (linked to occupational exposure and consumer products). Grouping is not exclusive and some sources may be part of multiple groups. For the moment, no hierarchical grouping will be included. The exposure sources will be a flat list of exposure sources deemed relevant in this task.
