### ISSUE TITLE
external exposure <> exposure pathway

### ISSUE THREAD

**Issue by dirkdevriendt** [eu-parc/aggregate-exposure-modelling#2]
I would think the pathway (a person got exposed to lead by eating eels once per month) would be the defining link for the external exposure and the others (source, route, surface, substance) would follow from that link, but I'd need to get a better view on actual examples to be able to form an opinion.

**Comment by jwkruisselbrink** [comment]
Comments from meeting (31/8):
- It was noted that the example was incorrect. However, the relationship between exposure pathway, source, and route should be corrected.
- Action point: Natalie and Amelie to make proposal.

**Comment by jwkruisselbrink** [comment]
Suggestion from Natalie:

![image](https://github.com/eu-parc/aggregate-exposure-modelling/assets/17898794/7999475b-8d5d-4384-b685-8b971619dc84)

**Comment by jwkruisselbrink** [comment]
Process workflow:

![image](https://github.com/eu-parc/aggregate-exposure-modelling/assets/17898794/08685fd1-645e-4fbf-ac8a-336738729175)

Entity relationship diagram proposal:

![image](https://github.com/eu-parc/aggregate-exposure-modelling/assets/17898794/3b932abf-b94b-46d1-b133-fd18790894db)

Example:

![image](https://github.com/eu-parc/aggregate-exposure-modelling/assets/17898794/73aba35b-9972-46ef-ab93-19a5d4e2144e)
