### ISSUE TITLE
Exposure factor

### ISSUE THREAD

**Issue by GoedeTNO** [eu-parc/aggregate-exposure-modelling#36]
Exposure factor
Currently, a definition is recited from Heinemeyer et al. 2022 - but it is unclear from which source in this publication (e.g. WHO, OECD, EPA, ECKA, etc).

Current definition in Glossary:
"Exposure factors are exposure parameters related to human behaviour and characteristics that help determine an individual's exposure to a substance."

Where "Exposure parameter" is defined as: "All (model) data that are necessary to calculate exposure, including exposure factor and substance concentrations in the different sources."
I could confirm this definition in the EU ExpoFacts Database who defines it as non-chemical exposure factors, and in the TR 079 – Exposure Factors Sourcebook for European Populations - who define it as Physiological Parameters, Time-Activity Patterns, Receptor Contact Rates (for contaminated land sites).

Proposal 1: leave the definition of "Exposure factor" as is but include an example such as "Time-Activity Patterns" that determines exposure (?). Alternatively, to include "Non-chemical and non-operational: in the definition of exposure factors. 

Proposal 2: expand on the definition of "Exposure parameter" (and also include in the CM). My interpretation is that it refers to an "Exposure determinant" commonly used in occupational exposures. In ECKA (R.14.5) Exposure determinants are a broad spectrum of factors that affects Worker exposure (including behavioural factors), such as:
• inherent properties of the substances, in a mixture or in an article; 
• the process type and the associated containment and degree of engineering
control; 
• operational conditions, e.g. temperature, in-use concentration, scale of use, 
duration and frequency;
• RMMs (exposure control) applied and the associated effectiveness.
Similarly - I would assume that this would also be relevant for consumer and environmental modelling.

**Comment by jwkruisselbrink** [comment]
First proposal based on discussion:

![image](https://github.com/eu-parc/aggregate-exposure-modelling/assets/17898794/55b704a5-5c71-4a74-abaf-16f25f66091d)
